Data to repo2
MarijaRomanenkova/newsongbird pull request #10
Opened 2022-12-30 12:36 UTC by MarijaRomanenkova

Please review. 
Tasks # 6
" переместить данные в репозиторий, и из нашего приложения делать запрос за этими данными. пока данные грузятся - показывать лоадер"

I have moved data to data file, and accessed it with json-server. 

I have also added unique ids to data. My original data has no unique ids. I hope this solved the problem?
Eslint keeps on warning on this issue for the file  answear.options  but I believe it should not be an issue anymore, should it?

2023-01-02 10:05 UTC, Viktarrudzenia requested changes
small fixes needed

2023-01-02 10:05 UTC, Viktarrudzenia commented on src/pages/loginform/loginform.component.jsx
> +  };
do we really need this method here?

2023-01-02 10:05 UTC, Viktarrudzenia commented on src/pages/signup/signup.jsx
> +  };
do we really need this method here?

2023-01-02 10:05 UTC, Viktarrudzenia commented on src/store/gameSlice.js
> +
extra line? or do you want separate axios with reduxjs and nonoid?

2023-01-02 10:05 UTC, Viktarrudzenia commented on src/store/gameSlice.js
> +const url = 'http://localhost:3500/birds';
it looks tricky
do we need this URL here?
if we move some variable in upper scope, it always named in UPPER_CASE_NAMING

2023-01-02 10:19 UTC, MarijaRomanenkova commented on src/pages/signup/signup.jsx
> +  };
fixed

2023-01-02 10:20 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +
fixed

2023-01-02 10:24 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +const url = 'http://localhost:3500/birds';
fixed, moved to axios.get('http://localhost:3500/birds')

2023-01-02 10:26 UTC, MarijaRomanenkova commented on src/pages/loginform/loginform.component.jsx
> +  };
fixed

2023-01-02 10:37 UTC, MarijaRomanenkova commented on src/pages/home/home.component.jsx
> +  }
fixed

2023-01-02 13:12 UTC, MarijaRomanenkova commented on src/components/loader/loader.module.scss
> +  height: 350px;
removed height

2023-01-02 13:37 UTC, MarijaRomanenkova commented on src/index.js
> +store.dispatch(getBirdsData());
Please advise.

2023-01-02 13:51 UTC, Viktarrudzenia commented on src/pages/home/home.component.jsx
> +  if (isQuestionaryDataLoading || !selectCorrectAnswerObject) {
also it looks like you need to select data from selectCorrectAnswerObject and then use condition, like:
const something = useSelector(selectCorrectAnswerObject)
?

2023-01-02 13:57 UTC, Viktarrudzenia commented on src/components/loader/loader.module.scss
> +  height: 350px;
not sure about removing it, just thinks about:
do we really set it to 350px; maybe it should min-height... or something not static based, if its a loader

2023-01-02 13:59 UTC, Viktarrudzenia commented on src/store/gameSlice.js
> +const url = 'http://localhost:3500/birds';
can we create an axios instance, put it inside the REACT_APP_BACKEND_URL variable from .env file, and use it instead of static?

so we'll simplify from axios.get('http://something/') to axios.get(/something)

2023-01-02 20:38 UTC, MarijaRomanenkova commented on src/components/loader/loader.module.scss
> +  height: 350px;
set height to max-height

2023-01-02 20:42 UTC, MarijaRomanenkova commented on src/index.js
> +store.dispatch(getBirdsData());
moved calling getbirdsData to <Home />  from useEffect.

2023-01-02 20:44 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +const url = 'http://localhost:3500/birds';
done

2023-01-02 20:44 UTC, MarijaRomanenkova commented on src/pages/home/home.component.jsx
> +  if (isQuestionaryDataLoading || !selectCorrectAnswerObject) {
fixed

2023-01-03 10:17 UTC, Viktarrudzenia requested changes
please add changes related to comments

2023-01-03 10:17 UTC, Viktarrudzenia commented on .env
> +√REACT_APP_BACKEND_URL =http://localhost:3500/birds
what is `√` ?
![image](https://user-images.githubusercontent.com/33637420/210336023-a62cfa0c-ff8e-4a2a-a7c5-733e4d4d513b.png)

2. it is better to keep pattern in .env without any spaces between `=`
3. .env file usually not uploaded to the git repository, and uploaded some example of .env file without variables inside (for example .env.example)
4. I'm not sure that if I use localhost:3500 in my environment it will be able to download the data from your repository. is this URL address correct for upload data from your github repo?

2023-01-03 10:17 UTC, Viktarrudzenia commented on src/App.js
> +  // eslint-disable-next-line no-console
do we really need this line?

2023-01-03 10:17 UTC, Viktarrudzenia commented on src/index.js
> +// eslint-disable-next-line no-console
do we really need this line?

2023-01-03 10:17 UTC, Viktarrudzenia commented on src/index.js
> +import { BrowserRouter } from 'react-router-dom';
import order

2023-01-03 10:17 UTC, Viktarrudzenia commented on src/pages/home/home.component.jsx
> +      {correctAnswerID !== 0 && <Game />}
I'm not sure about all JSX in this component, because
you render Game ONLY when we got data a, but my assumption for this web app -> show GAME always (even without data), but at the top of it add loader, while we send request

2023-01-03 11:05 UTC, MarijaRomanenkova commented on .env
> +√REACT_APP_BACKEND_URL =http://localhost:3500/birds
1.  fixed
2. fixed
3. added .env .to gitignore, created .env.example
4. It will work. You will neet to open second terminal and type
$ npx json-server -p 3500 -w data/db.json
 and then run React project  $ npm start in the first terminal window.

2023-01-03 11:05 UTC, MarijaRomanenkova commented on src/App.js
> +  // eslint-disable-next-line no-console
fixed

2023-01-03 11:05 UTC, MarijaRomanenkova commented on src/index.js
> +// eslint-disable-next-line no-console
fixed

2023-01-03 11:06 UTC, MarijaRomanenkova commented on src/index.js
> +import { BrowserRouter } from 'react-router-dom';
fixed

2023-01-03 11:13 UTC, MarijaRomanenkova commented on src/pages/home/home.component.jsx
> +      {(isQuestionaryDataLoading === true || correctAnswerID === 0) && (
fixed

2023-01-03 11:52 UTC, MarijaRomanenkova commented on src/pages/home/home.component.jsx
> +      {correctAnswerID !== 0 && <Game />}
done with suspense

2023-01-03 11:52 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +  correctAnswerID: 0,
fixed

2023-01-03 12:28 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +  const response = await axios.get(process.env.REACT_APP_BACKEND_URL);
Done. Well I think I did it. Please check

2023-01-03 12:34 UTC, Viktarrudzenia commented on .env
> +√REACT_APP_BACKEND_URL =http://localhost:3500/birds
4. yes, it is possible in a way that you are saying, but if I want just run your project only (FE part), can I have the data in that case?
We want to separate FE and BE logic, so I want just run the FE app and got all data, let's focus on that case

2023-01-03 12:35 UTC, Viktarrudzenia commented on .env
> +REACT_APP_BACKEND_URL=http://localhost:3500
it looks like the .env file should not be here? :) just on your local machine? :)

2023-01-03 12:37 UTC, Viktarrudzenia commented on .env.example
> +REACT_APP_BACKEND_URL=http://localhost:3500/birds
usually it looks like:
`REACT_APP_BACKEND_URL=`
or in a list:

`REACT_APP_BACKEND_URL=`
`REACT_APP_SOME_ANOTHER_VARIABLE=`

and inside the README.md we can have some information about where or how to get the value for REACT_APP_BACKEND_URL

2023-01-03 12:39 UTC, Viktarrudzenia commented on README.md
> +5. Open [http://localhost:3000](http://localhost:3000) to view it in your browser.
it looks like it could be open not only on :3000
let's try to npm start in 2 terminals, in the second, you'll have an option to run it on 3001 and so on

But, yes, by default it will be port 3000 of course

2023-01-03 12:42 UTC, Viktarrudzenia commented on src/pages/home/home.component.jsx
> +      </Suspense>
not sure that Suspense here will be a good option

I just mentioned about:

<div>
<Game />
{isRequestLoading && <Loader />
</div>

and every time when isRequestLoading  -> we'll have an Loader on our app. if we'll add this loader absolute position, and it's parent any position instead of static -> it can help us to show the loader just above our Game component

2023-01-03 12:43 UTC, Viktarrudzenia commented on src/pages/home/home.component.jsx
> +      {correctAnswerID !== 0 && <Game />}
not sure about suspense

2023-01-03 13:03 UTC, MarijaRomanenkova commented on .env
> +REACT_APP_BACKEND_URL=http://localhost:3500
yes. fixed

2023-01-03 14:27 UTC, MarijaRomanenkova commented on README.md
> +5. Open [http://localhost:3000](http://localhost:3000) to view it in your browser.
eliminated

2023-01-03 14:34 UTC, MarijaRomanenkova commented on .env
> +√REACT_APP_BACKEND_URL =http://localhost:3500/birds
done

2023-01-05 14:00 UTC, Viktarrudzenia approved these changes
code looks good, great job

2023-01-05 19:58 UTC, merged