Languages
MarijaRomanenkova/newsongbird pull request #12
Opened 2023-01-11 13:09 UTC by MarijaRomanenkova

2023-01-11 16:43 UTC, viktarrudzenia requested changes
please look into the comments and fix where necessary

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +                id="answer-option-details_dummy2"
i'm sure that id's should represent something about the text inside, dummy text looks not a lot of descriptive
can we use for these id's something more meaningful?

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/game/index.js
> +  const language = useSelector(selectLanguage);
I'm not sure that we need to store language inside redux, can we get it from react-intl?

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/game/index.js
> +  const url = useSelector(selectURL);
i'm not sure about store URL for data inside redux

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/game/index.js
> +  }, [language]);
ask about this moment inside next call conversation, and we'll discuss how it will work in real cases

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/language-switch/index.jsx
> +  };
not sure about changing the language inside redux, can we switch the language inside react-intl (provider)?

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/language-switch/index.module.scss
> +	 padding: 0 0.2rem;
wrong indent

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/language-switch/index.module.scss
> +    max-height:100%;
prettier all file

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/navigation/navigation.module.scss
>    }
do we really need this?

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/navigation/navigation.module.scss
> +    align-items: center;
prettier file

2023-01-11 16:43 UTC, viktarrudzenia commented on src/components/score/score.component.jsx
>  import { selectScore } from 'store/gameSlice';
imports order

2023-01-11 16:43 UTC, viktarrudzenia commented on src/lang/en.json
> +  "answer-option-details_dummy2": "Select a bird from the list and check if your answer is correct.",
why somewhere used camelCasePattern and somewhere dash-space-pattern?
if it is not something meaningful - please use one pattern for all id's it could be one of them

2023-01-11 16:43 UTC, viktarrudzenia commented on src/lang/en.json
> +  "answer-option-details_dummy2": "Select a bird from the list and check if your answer is correct.",
etc. somewhere used mixed patter like: camelCase_withunderscore
looks tricky a bit, let's use 1 pattern for all id's

2023-01-11 16:43 UTC, viktarrudzenia commented on src/store/gameSlice.js
> +  url: '/dataen.json',
not sure about three these values for storing inside redux

2023-01-11 16:43 UTC, viktarrudzenia commented on src/store/gameSlice.js
> +  languageList,
not sure about store it here

2023-01-12 06:38 UTC, MarijaRomanenkova commented on src/App.js
> +/* eslint-disable no-unused-vars */
fixed

2023-01-12 06:53 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +                id="answer-option-details_dummy2"
changed to game-rules_text

2023-01-12 06:56 UTC, MarijaRomanenkova commented on src/components/language-switch/index.module.scss
> +	 padding: 0 0.2rem;
fixed

2023-01-12 06:56 UTC, MarijaRomanenkova commented on src/components/language-switch/index.module.scss
> +    max-height:100%;
fixed

2023-01-12 07:02 UTC, MarijaRomanenkova commented on src/components/navigation/navigation.module.scss
>    }
Fixed. Absolutely unnecessary.

2023-01-12 07:05 UTC, MarijaRomanenkova commented on src/components/score/score.component.jsx
>  import { selectScore } from 'store/gameSlice';
fixed

2023-01-12 07:33 UTC, MarijaRomanenkova commented on src/lang/en.json
> +  "answer-option-details_dummy2": "Select a bird from the list and check if your answer is correct.",
Done. all to dash-space-pattern.

2023-01-12 07:33 UTC, MarijaRomanenkova commented on babelrc
> +{
Fixed. File not needed.

2023-01-12 08:10 UTC, MarijaRomanenkova commented on package.json
> +    "babel-plugin-react-intl": "^8.2.25",
Fixed. Not needed.

2023-01-12 13:54 UTC, MarijaRomanenkova commented on src/components/game/index.js
> +  const language = useSelector(selectLanguage);
Done. moved to intl

2023-01-12 13:55 UTC, MarijaRomanenkova commented on src/components/game/index.js
> +  }, [language]);
OK

2023-01-12 13:55 UTC, MarijaRomanenkova commented on src/components/language-switch/index.jsx
> +  };
Done

2023-01-13 09:13 UTC, viktarrudzenia commented on src/App.js
> +  }
not sure about storing it in localstorage
is it possible to move this logic to react-intl instance?

2023-01-13 09:13 UTC, viktarrudzenia commented on src/App.js
> +  const [currentLocale, setCurrentLocale] = useState(getInitialLocal());
not sure about storing it in localstorage
is it possible to move this logic to react-intl instance?

2023-01-13 09:13 UTC, viktarrudzenia commented on src/App.js
> +  };
not sure about storing it in localstorage
is it possible to move this logic to react-intl instance?

2023-01-13 09:17 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +                id="game-rules-text-2"
is it possible to improve naming for id to something like

"game-rules-text"

-> 

"game-rules-listen-song"

?

"game-rules-text-2"

-> 

"game-rules-select-answer" 
?

because! let's have an example
We decide to add a new language, Italian as example. and gives 1 translation to translator with all id's and texts, it will be better to illustrate the message if our id's will contain something related to text inside

2023-01-13 09:18 UTC, viktarrudzenia commented on src/components/language-switch/index.module.scss
> +    max-height:100%;
are you sure? 
![image](https://user-images.githubusercontent.com/33637420/212283504-64e6b72b-70cf-4587-9c1a-6f357e35e6b4.png)
it looks like not fixed

2023-01-13 09:18 UTC, viktarrudzenia commented on src/components/navigation/navigation.module.scss
> +    align-items: center;
![image](https://user-images.githubusercontent.com/33637420/212283639-c367b7ff-8c6f-4fe4-8f23-044b60517193.png)
not sure

2023-01-18 08:47 UTC, viktarrudzenia requested changes
please fix comments

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  const { i18n } = useTranslation();
why do we use two lines here? can we use 1?

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  const language = `_${i18n.language.toString()}`;
do we  really need .toString() here?

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  const language = `_${i18n.language.toString()}`;
it is not clear why we are adding '_' at the beginning of the language string.

2023-01-18 08:47 UTC, viktarrudzenia commented on data.json
> +        "name_ru":"Ласточка",
you misunderstand me maybe,
I mean not this example
I mean that data json will begin like this:
{en: [], lt: [], ru: []}
and all three [] -> will be the same, but with different translations for text

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/categories/categories.component.jsx
> +            index === currentLevel - 3
magic number antipattern

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  const language = `_${i18n.language.toString()}`;
all of these `_language` will be unnecessary with my pattern that I wrote above

2023-01-18 08:47 UTC, viktarrudzenia commented on src/components/language-switch/index.jsx
> +    dispatch(switchLanguage(lng));
do we really need this state in redux?

2023-01-18 08:47 UTC, viktarrudzenia commented on src/index.js
> +import './i18next';
import order

2023-01-18 08:47 UTC, viktarrudzenia commented on src/pages/signup/signup.jsx
> +              ) : null}
do we really need this construction with

something ? <div /> : null?

can we redo it to 

condition && <div /> 

?

2023-01-18 08:47 UTC, viktarrudzenia commented on src/pages/signup/signup.jsx
> +              ) : null}
redo in all file

2023-01-18 08:47 UTC, viktarrudzenia commented on src/store/gameSlice.js
> +}
a little bit tricky

2023-01-18 09:21 UTC, MarijaRomanenkova commented on src/components/navigation/navigation.module.scss
> +    align-items: center;
checked and fixed

2023-01-18 10:10 UTC, MarijaRomanenkova commented on src/App.js
> +  }
fixed

2023-01-18 10:10 UTC, MarijaRomanenkova commented on src/App.js
> +  const [currentLocale, setCurrentLocale] = useState(getInitialLocal());
fixed

2023-01-18 10:10 UTC, MarijaRomanenkova commented on src/App.js
> +  };
fixed

2023-01-18 10:13 UTC, MarijaRomanenkova commented on src/index.js
> +import './i18next';
fixed

2023-01-18 14:24 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +                id="game-rules-text-2"
done

2023-01-23 09:59 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  const { i18n } = useTranslation();
fixed

2023-01-23 09:59 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  const language = `_${i18n.language.toString()}`;
fixed

2023-01-23 09:59 UTC, MarijaRomanenkova commented on data.json
> +        "name_ru":"Ласточка",
fixed

2023-01-23 09:59 UTC, MarijaRomanenkova commented on src/components/categories/categories.component.jsx
> +            index === currentLevel - 3
fixed

2023-01-23 09:59 UTC, MarijaRomanenkova commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  const language = `_${i18n.language.toString()}`;
fixed

2023-01-23 09:59 UTC, MarijaRomanenkova commented on src/components/language-switch/index.jsx
> +    dispatch(switchLanguage(lng));
fixed

2023-01-23 10:00 UTC, MarijaRomanenkova commented on src/pages/signup/signup.jsx
> +              ) : null}
fixed

2023-01-23 10:00 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +  currentLevel: 3,
fixed

2023-01-23 10:00 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +}
fixed

2023-01-23 10:00 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +    },
fixed. moved language out

2023-01-23 12:35 UTC, viktarrudzenia approved these changes
oh, now it looks really good, great job!
just fix please small things I left inside comments above and after that feel free to merge this PR into main with 'squash' option

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +/* eslint-disable prefer-destructuring */
it's a good option, let's use destructuring where it is needed

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  const language = i18n.language;
here destructuring needed

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  function findByIndex(option, index) {
we can improve naming here,

findWHATByIndex ?

findCurrentLevelByIndex?

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/categories/categories.component.jsx
> +/* eslint-disable prefer-destructuring */
let's use destructuring where possible

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  // eslint-disable-next-line prefer-destructuring
let's use destructuring where possible

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  function findByIndex(option, index) {
please improve naming

2023-01-23 12:35 UTC, viktarrudzenia commented on src/components/language-switch/index.jsx
> +  };
do we really need this function here? 

can we just get it from useTranslation?

2023-01-23 12:46 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  function findByIndex(option, index) {
fixed

2023-01-23 12:49 UTC, MarijaRomanenkova commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  // eslint-disable-next-line prefer-destructuring
fixed

2023-01-23 12:49 UTC, MarijaRomanenkova commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  function findByIndex(option, index) {
fixed

2023-01-23 12:59 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +/* eslint-disable prefer-destructuring */
fixed

2023-01-23 13:00 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  const language = i18n.language;
done

2023-01-23 13:00 UTC, MarijaRomanenkova commented on src/components/categories/categories.component.jsx
> +/* eslint-disable prefer-destructuring */
done

2023-01-23 13:04 UTC, MarijaRomanenkova commented on src/components/language-switch/index.jsx
> +  };
Done!

2023-01-23 14:10 UTC, merged