craco
MarijaRomanenkova/newsongbird pull request #15
Opened 2023-01-16 08:03 UTC by MarijaRomanenkova

2023-01-17 08:17 UTC, viktarrudzenia requested changes
looks good, just small comments

2023-01-17 08:17 UTC, viktarrudzenia commented on craco.config.js
> +
extra spaces?

2023-01-17 08:17 UTC, viktarrudzenia commented on craco.config.js
> +        },
is it worked well? is it okay to paste the necessary modules?

2023-01-17 08:17 UTC, viktarrudzenia commented on package.json
> +    "craco-sass-resources-loader": "^1.1.0",
maybe it will be better to install this dependency as devDependency?

2023-01-17 14:27 UTC, MarijaRomanenkova commented on craco.config.js
> +        },
Yes, it works, I have romoved all imports of variables.scss and mixins and it works absolutely the same.

2023-01-17 14:27 UTC, MarijaRomanenkova commented on package.json
> +    "craco-sass-resources-loader": "^1.1.0",
fixed. moved to devdependencies

2023-01-17 14:28 UTC, MarijaRomanenkova commented on craco.config.js
> +
fixed

2023-01-18 08:49 UTC, viktarrudzenia commented on package.json
> +    "sass-resources-loader": "^2.2.5",
extra spaces ?

2023-01-18 08:49 UTC, viktarrudzenia approved these changes
looks good, could be merged into dev :)

2023-01-18 08:49 UTC, merged