Redux toolkit
MarijaRomanenkova/newsongbird pull request #8
Opened 2022-12-26 15:14 UTC by MarijaRomanenkova

2022-12-27 11:08 UTC, Viktarrudzenia requested changes
please look into the comments, fix them, then write inside the thread something like:
'fixed', and then I will close thread if all be good

or answer in the thread your opinion and I will understand that you have something to discuss or etc. 

please do not close this PR, all changes add exactly to this PR

2022-12-27 11:08 UTC, Viktarrudzenia commented on src/pages/notfound/notfound.component.jsx
> +import { availableRoutesList } from 'routes/availableRoutesList';
imports order

2022-12-27 11:08 UTC, Viktarrudzenia commented on src/pages/signup/signup.jsx
> +import 'react-toastify/dist/ReactToastify.css';
oh, the second toastcontainer, as I mentioned above, can we move it to the very beginning as we made with another providers?

2022-12-27 11:08 UTC, Viktarrudzenia commented on src/schemas/index.js
> +const passwordRules = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{5,}$/;
it is better to name this RegExp in a way what exactly this RegExp do OR (more better as we'll have a lot of words) add a comment above this line to describe what exactly check this regexp

2022-12-27 11:55 UTC, MarijaRomanenkova commented on .gitignore
> +.vscode/extensions.json
Fixed

2022-12-27 11:55 UTC, MarijaRomanenkova commented on package.json
> +  "name": "songbird-redux",
fixed

2022-12-27 11:56 UTC, MarijaRomanenkova commented on src/App.module.scss
>  @import 'scss-source/mixins.scss';
fixed

2022-12-27 11:57 UTC, MarijaRomanenkova commented on src/App.test.js
> +import Home from './pages/home/home';
fixed

2022-12-27 11:58 UTC, MarijaRomanenkova commented on src/pages/notfound/notfound.component.jsx
> +import { availableRoutesList } from 'routes/availableRoutesList';
Order or just a gap between lines needed?

2022-12-27 12:18 UTC, MarijaRomanenkova commented on src/schemas/index.js
> +const passwordRules = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{5,}$/;
fixed

2022-12-27 12:24 UTC, MarijaRomanenkova commented on src/pages/loginform/loginform.component.jsx
> +import 'react-toastify/dist/ReactToastify.css';
fixed

2022-12-27 12:27 UTC, MarijaRomanenkova commented on src/pages/loginform/loginform.component.jsx
> +import { toast, ToastContainer, Zoom } from 'react-toastify';
fixed

2022-12-27 14:59 UTC, MarijaRomanenkova commented on src/App.js
> +        <Route path={availableRoutesList.NOT_FOUND} element={<NotFound />} />
Will be made in separate PR

2022-12-28 13:41 UTC, Viktarrudzenia approved these changes
looks good, great job @MarijaRomanenkova

2022-12-28 13:41 UTC, Viktarrudzenia commented on src/pages/loginform/loginform.component.jsx
> +  };
could be done in the next PR
it will be cool to move these settings to ToastContainer initialization
and just use toasts like:

toast.success(message);

2022-12-28 13:41 UTC, Viktarrudzenia commented on src/pages/signup/signup.jsx
> +  };
same as above, if we'll initialize these settings in toastContainer we can simplify usage to

toast.success(someMessage)

2022-12-28 13:43 UTC, Viktarrudzenia requested changes
not fixed all comments

2022-12-28 14:00 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  win,
fixed

2022-12-28 14:05 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +    selectCurrentCategoryArray
fixed

2022-12-28 14:39 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  const correctAnswer = useSelector(selectCurrentCorrectAnswerObject) || [];
fixed

2022-12-28 14:43 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +    dispatch(choose());
fixed

2022-12-28 14:43 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +      dispatch(win());
fixed

2022-12-28 14:44 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +    dispatch(nextLevel());
fixed : switchToNextLevel

2022-12-29 06:06 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +              key={item.index + item.name}
fixed

2022-12-29 06:08 UTC, MarijaRomanenkova commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  const correctAnswer = useSelector(selectCurrentCorrectAnswerObject);
fixed

2022-12-29 06:10 UTC, MarijaRomanenkova commented on src/components/gameOver/gameOver.component.jsx
> +            onClick={() => dispatch(newGame())}
fixed

2022-12-29 06:11 UTC, MarijaRomanenkova commented on src/components/navigation/navigation.component.jsx
> +import styles from './navigation.module.scss';
fixed

2022-12-29 06:11 UTC, MarijaRomanenkova commented on src/index.js
> +import { BrowserRouter } from 'react-router-dom';
fixed

2022-12-29 06:13 UTC, MarijaRomanenkova commented on src/pages/home/home.jsx
> +
fixed

2022-12-29 06:15 UTC, MarijaRomanenkova commented on src/pages/home/home.module.scss
> +@import 'scss-source/mixins.scss';
Got it

2022-12-29 06:40 UTC, MarijaRomanenkova commented on src/pages/signup/signup.jsx
> +  };
fixed

2022-12-29 06:55 UTC, MarijaRomanenkova commented on src/pages/loginform/loginform.component.jsx
> +  };
fixed

2022-12-29 16:55 UTC, Viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +              key={item.index + item.name}
we need to use something unique, and `id` in most cases unique for all values inside
so can we use .id here?

if we don't have an alert in this case where using index+name -> it is not meaning that we are wrote a good code :(

2022-12-29 17:00 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +
extra line

2022-12-29 17:04 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +
extra lines

2022-12-29 17:05 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +  baseURL: "http://localhost:3000/birds",
not sure about baseURL with static HTTP address with a static port
maybe it will be better to move the base URL to .env and use it from 

also not sure about creating apiInstance in this file, maybe it will be better to move this API instance somewhere above

2022-12-29 17:05 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +  },
do we really need these configs?

2022-12-29 17:06 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +export const initialState = {
it will be better to name this initalState to something more meaningful, because in the future we can have a lot of initialStates in redux

2022-12-29 17:07 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +// our slice
not sure about this comment

2022-12-29 17:08 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +// fetch all items
not sure about comment here

2022-12-29 17:08 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +export default ItemsPage;
why do we have this component here? do we really need it here?

2022-12-29 17:09 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +    return items.map((i) => <li> {i.name} </li>);
missed key

2022-12-29 17:10 UTC, Viktarrudzenia commented on src/store/dataSlice.js
> +import { createSlice} from "@reduxjs/toolkit";
to all this file? if it a something for debugging - okay, skip all my comments, and just delete this file from this PR, so we can merge all of above to `main`

2022-12-29 17:11 UTC, Viktarrudzenia commented on src/store/store.js
> +import gameReducer from './gameSlice';
extra line

2022-12-29 17:12 UTC, Viktarrudzenia requested changes
comments,
if we can delete src/store/dataSlice.js, it looks like we can merge this PR to main

2022-12-29 17:22 UTC, MarijaRomanenkova commented on src/store/dataSlice.js
> +
fixed

2022-12-29 17:23 UTC, MarijaRomanenkova commented on src/store/dataSlice.js
> +export default ItemsPage;
fixed: left the example unintentionally. file shoul be deleted

2022-12-30 06:02 UTC, merged