Data to repo
MarijaRomanenkova/newsongbird pull request #9
Opened 2022-12-28 13:07 UTC by MarijaRomanenkova

Please help figuring out what's wrong. 
Trying to fetch data from local repo with asyncThunk

2022-12-28 13:26 UTC, Viktarrudzenia requested changes
please look into comments

2022-12-28 13:26 UTC, Viktarrudzenia commented on public/data.json
> +[
it is better not to add this data to the /public folder. because all data inside /public folder will be in the final build
But I'm not sure that we need it inside final build

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/components/answerOptions/answerOptions.component.jsx
> +  }
it is better to redo this structure from JS oriented to JSX oriented
{isDataLoading && <div>Loading...</div>}

the naming of variable also should be more meaningful
isQuestionaryDataLoading (maybe or etc.)

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/components/categories/categories.component.jsx
> +  }
the same as above,

2. also not sure that we need all these loaders for each component.

maybe it will be more clear to add 1 loader to the full content where our app should be displayed

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  }
same as above

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/components/gameOver/gameOver.component.jsx
> +  }
same as above

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/store/gameSlice.js
> +);
try to use the default structure from the example:

![image](https://user-images.githubusercontent.com/33637420/209819184-b1c862da-83c8-4041-8c12-6d7452490507.png)

the example with creating createAsyncThunk not obvious enouth

2022-12-28 13:26 UTC, Viktarrudzenia commented on src/store/gameSlice.js
> +);
also you should add dispatch loaders to our async function, to display loader when the request sending to the BE

2022-12-29 07:27 UTC, MarijaRomanenkova commented on src/components/answerOptions/answerOptions.component.jsx
> +  }
fixed

2022-12-29 07:28 UTC, MarijaRomanenkova commented on src/components/categories/categories.component.jsx
> +  }
fixed

2022-12-29 07:28 UTC, MarijaRomanenkova commented on src/components/correctAnswer/correctAnswer.component.jsx
> +  }
fixed

2022-12-29 07:28 UTC, MarijaRomanenkova commented on src/components/gameOver/gameOver.component.jsx
> +  }
fixed

2022-12-30 12:11 UTC, MarijaRomanenkova commented on public/data.json
> +[
fixed. moved to data folder, used json server to get to the data

2022-12-30 12:15 UTC, MarijaRomanenkova commented on src/store/gameSlice.js
> +);
Can we please discuss this one. I did not figure out how to get data inside setTimeout. My current piece works, but I didn't manage to use setTimeout on it.

2023-01-02 20:36 UTC, closed without merging